package gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class FormularioGestionar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioGestionar.class.getName());
    private final String modo;
    private final Gestion gestion;
    private final VentanaGestionar ventanaAnterior;

    /**
     * Creates new form FormularioRegistro
     */
    public FormularioGestionar(String modo, Gestion gestion, VentanaGestionar ventanaAnterior) {
        initComponents();
        
        this.modo = modo;
        this.gestion = gestion;
        this.ventanaAnterior = ventanaAnterior;
        
        cargarEscuderias();
        cargarAutos();
        cargarPilotos();
        cargarMecanicos();

        // --- BLOQUE QUE OCULTA TODAS LAS VARIABLES PARA SOLO USAR LAS QUE NECESITAMOS ---
    
        lblCampoEsc.setVisible(false);
        comboCampoEsc.setVisible(true);
        btnBorrarEsc.setVisible(false);
        btnAsociar.setVisible(false);
        btnEliminarAsociacion.setVisible(false);
        
        lblCampo2.setVisible(false);
        comboCampoPiloto.setVisible(false);
        comboCampoAuto.setVisible(false);
        comboCampoMecanico.setVisible(false);
    
        lblCampodF.setVisible(false);
        txtCampodF.setVisible(false);
    
        lblCampohF.setVisible(false);
        txtCampohF.setVisible(false);
        
        switch (modo) {
        case "PILOTO":
            this.setTitle("Registrar Piloto");
            
            tituloRegistro.setText(modo);
            
            // "Prendemos" y configuramos los campos para Piloto
            lblCampoEsc.setText("Escudería:");
            lblCampoEsc.setVisible(true); 
            comboCampoEsc.setVisible(true); 
            
            lblCampo2.setText("Piloto:");
            lblCampo2.setVisible(true); 
            comboCampoPiloto.setVisible(true); 
            
            lblCampodF.setText("Desde fecha:");
            lblCampodF.setVisible(true); 
            txtCampodF.setVisible(true); 
            
            lblCampohF.setText("Hasta fecha:");
            lblCampohF.setVisible(true); 
            txtCampohF.setVisible(true); 
            
            
            btnAsociar.setVisible(true);
            btnEliminarAsociacion.setVisible(true);
            
            
            break;
            
        case "MECANICO":
            this.setTitle("Registrar Mecánico");
            
            tituloRegistro.setText(modo);
            
            lblCampoEsc.setText("Escudería:");
            lblCampoEsc.setVisible(true); 
            comboCampoEsc.setVisible(true); 
            
            lblCampo2.setText("Mecánico:");
            lblCampo2.setVisible(true); 
            comboCampoMecanico.setVisible(true); 
            
            lblCampodF.setText("Desde fecha:");
            lblCampodF.setVisible(true); 
            txtCampodF.setVisible(true); 
            
            lblCampohF.setText("Hasta fecha:");
            lblCampohF.setVisible(true); 
            txtCampohF.setVisible(true); 
            
            btnAsociar.setVisible(true);
            btnEliminarAsociacion.setVisible(true);
            
            break;
            
            case "AUTO":
            this.setTitle("Registrar Auto");
            
            tituloRegistro.setText(modo);
            
            // "Prendemos" y configuramos los campos para Piloto
            lblCampoEsc.setText("Escudería:");
            lblCampoEsc.setVisible(true); 
            comboCampoEsc.setVisible(true); 
            
            lblCampo2.setText("Auto:");
            lblCampo2.setVisible(true); 
            comboCampoAuto.setVisible(true); 
            
            btnAsociar.setVisible(true);
            btnEliminarAsociacion.setVisible(true);
            break;
            
            case "BORRAR_ESCUDERIA":
            this.setTitle("Registrar Escudería");
            
            tituloRegistro.setText(modo);
            
            lblCampoEsc.setText("Escudería:");
            lblCampoEsc.setVisible(true); 
            comboCampoEsc.setVisible(true); 
            btnBorrarEsc.setVisible(true);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bntVolver = new javax.swing.JButton();
        tituloRegistro = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        comboCampoEsc = new javax.swing.JComboBox<>();
        comboCampoPiloto = new javax.swing.JComboBox<>();
        comboCampoAuto = new javax.swing.JComboBox<>();
        comboCampoMecanico = new javax.swing.JComboBox<>();
        lblCampoEsc = new javax.swing.JLabel();
        lblCampo2 = new javax.swing.JLabel();
        lblCampodF = new javax.swing.JLabel();
        lblCampohF = new javax.swing.JLabel();
        txtCampodF = new javax.swing.JTextField();
        txtCampohF = new javax.swing.JTextField();
        btnBorrarEsc = new javax.swing.JButton();
        btnAsociar = new javax.swing.JButton();
        btnEliminarAsociacion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        fondoimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(null);

        bntVolver.setText("VOLVER");
        bntVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVolverActionPerformed(evt);
            }
        });
        jPanel2.add(bntVolver);
        bntVolver.setBounds(6, 10, 90, 27);

        tituloRegistro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloRegistro.setText("Gestionar");
        tituloRegistro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(tituloRegistro);
        tituloRegistro.setBounds(0, 0, 380, 60);

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 60));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(comboCampoEsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 150, 30));
        jPanel3.add(comboCampoPiloto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 150, 30));
        jPanel3.add(comboCampoAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 150, 30));
        jPanel3.add(comboCampoMecanico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 150, 30));

        lblCampoEsc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCampoEsc.setText("lbl1");
        jPanel3.add(lblCampoEsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 25));

        lblCampo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCampo2.setText("lbl2");
        jPanel3.add(lblCampo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 25));

        lblCampodF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCampodF.setText("lbl2");
        jPanel3.add(lblCampodF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 20));

        lblCampohF.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCampohF.setText("lbl2");
        jPanel3.add(lblCampohF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, 30));
        jPanel3.add(txtCampodF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 150, 30));
        jPanel3.add(txtCampohF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 150, 30));

        btnBorrarEsc.setText("BORRAR");
        btnBorrarEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarEscActionPerformed(evt);
            }
        });
        jPanel3.add(btnBorrarEsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 100, 30));

        btnAsociar.setText("ASOCIAR");
        btnAsociar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsociarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAsociar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 110, 30));

        btnEliminarAsociacion.setText("ELIMINAR");
        btnEliminarAsociacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAsociacionActionPerformed(evt);
            }
        });
        jPanel3.add(btnEliminarAsociacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 110, 30));

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 380, 340));

        fondoimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/f1logo.png"))); // NOI18N
        fondoimg.setPreferredSize(new java.awt.Dimension(310, 320));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoimg, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoimg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 320, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarEscActionPerformed
        try {
        switch (this.modo) {
            case "BORRAR_ESCUDERIA":
                    Escuderia esc = (Escuderia) comboCampoEsc.getSelectedItem();
                    int rpta = JOptionPane.showConfirmDialog(this, 
                "¿ESTÁ SEGURO?\nBorrar '" + esc.getNombre() + 
                "' también borrará todos sus autos y romperá todos sus contratos de pilotos y mecánicos.", 
                "Confirmar Borrado en Cascada", 
            JOptionPane.YES_NO_OPTION, 
            JOptionPane.WARNING_MESSAGE);
        
            if (rpta == JOptionPane.YES_OPTION) {
            // Llama al método de borrado en cascada que ya tenés en Gestion.java
            this.gestion.borrarEscuderia(esc); 
            
            JOptionPane.showMessageDialog(this, "Escudería borrada exitosamente.");
            cargarEscuderias(); // Refresca el combo (la escudería ya no existe)
            }
                    break;
            }
        } catch (Exception e) {
    // Si 'parseInt' falla, el código salta acá y la app NO crashea.
        JOptionPane.showMessageDialog(this, "El ID debe ser un número válido.");
    }//GEN-LAST:event_btnBorrarEscActionPerformed
    }
    
    private void bntVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVolverActionPerformed
        this.ventanaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bntVolverActionPerformed

    private void btnEliminarAsociacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAsociacionActionPerformed
        try {
        // Pedimos confirmación genérica
        int rpta = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro que desea borrar esta asociación?", 
                "Confirmar Borrado", 
                JOptionPane.YES_NO_OPTION);
        
        if (rpta != JOptionPane.YES_OPTION) {
            return; // El usuario canceló
        }

        switch (this.modo) {
            
            case "PILOTO":
                Piloto pil = (Piloto) comboCampoPiloto.getSelectedItem();
                Escuderia escPil = (Escuderia) comboCampoEsc.getSelectedItem();
                if (pil == null || escPil == null) {
                    throw new Exception("Debe seleccionar un Piloto y una Escudería.");
                }
                
                // Llama al método para romper el contrato N-a-N de Piloto
                // (Este método ya lo tenés en Gestion.java)
                gestion.darDeBajaPilotoEscuderia(pil, escPil); 
                
                JOptionPane.showMessageDialog(this, "Contrato de Piloto borrado.");
                break;

            case "MECANICO":
                Mecanico mec = (Mecanico) comboCampoMecanico.getSelectedItem();
                Escuderia escMec = (Escuderia) comboCampoEsc.getSelectedItem();
                if (mec == null || escMec == null) {
                    throw new Exception("Debe seleccionar un Mecánico y una Escudería.");
                }
                
                // Llama al método para romper la asociación N-a-N de Mecánico
                // (Este método ya lo tenés en Gestion.java)
                gestion.darDeBajaMecanicoEscuderia(mec, escMec);
                
                JOptionPane.showMessageDialog(this, "Asociación de Mecánico borrada.");
                break;
                
            case "AUTO":
                // Este botón no debería estar visible en el modo AUTO.
                // La "baja" de un auto (darDeBajaAutoEscuderia) es un borrado completo,
                // no una desasociación. Si querés un botón de borrar auto,
                // debería ser el 'bntBorrar' y no 'btnEliminarAsociacion'.
                break;
        }
        } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error en la operación", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarAsociacionActionPerformed

    private void btnAsociarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsociarActionPerformed
        try {
        // El switch decide qué lógica ejecutar basado en el modo
        switch (this.modo) {
            
            // --- FLUJO PILOTO (N-a-N con Fechas) ---
            case "PILOTO": {
                // 1. Leer datos
                Piloto pil = (Piloto) comboCampoPiloto.getSelectedItem();
                Escuderia escPil = (Escuderia) comboCampoEsc.getSelectedItem();
                String desde = txtCampodF.getText();
                String hasta = txtCampohF.getText();
                
                // 2. Validar
                if (pil == null || escPil == null || desde.isEmpty() || hasta.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar Piloto, Escudería y completar ambas fechas.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                }
                
                // 3. Llamar a la lógica
                gestion.gestionarPilotoEscuderia(pil, escPil, desde, hasta);
                JOptionPane.showMessageDialog(this, "Contrato de Piloto guardado.");
                break;
            }
                
//             --- FLUJO AUTO (1-a-N Reasignar) ---
            case "AUTO": {
                // 1. Leer datos
                Auto auto = (Auto) comboCampoAuto.getSelectedItem();
                Escuderia nuevaEscuderia = (Escuderia) comboCampoEsc.getSelectedItem();
                
                
                // 2. Validar
                if (auto == null || nuevaEscuderia == null) {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un Auto y la Nueva Escudería.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                }

                // 3. Llamar a la lógica
                gestion.gestionarAutoEscuderia(auto, nuevaEscuderia); 
                JOptionPane.showMessageDialog(this, "Auto reasignado exitosamente.");
                break;
            }

            // --- FLUJO MECÁNICO (N-a-N simple) ---
            case "MECANICO": {
                // 1. Leer datos
                Mecanico mec = (Mecanico) comboCampoMecanico.getSelectedItem();
                Escuderia escMec = (Escuderia) comboCampoEsc.getSelectedItem();
                String desde = txtCampodF.getText();
                String hasta = txtCampohF.getText();
                
                // 2. Validar
                if (mec == null || escMec == null || desde == null || hasta == null) {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar un Mecánico y una Escudería.", "Error", JOptionPane.ERROR_MESSAGE);
                    break;
                }
                
                // 3. Llamar a la lógica
                gestion.gestionarMecanicoEscuderia(mec, escMec, desde, hasta); 
                JOptionPane.showMessageDialog(this, "Mecánico asociado exitosamente.");
                break;
            }
        }
    } catch (Exception e) {
        // Captura cualquier error de lógica (como "El auto ya pertenece a esa escudería")
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error en la operación", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAsociarActionPerformed

    private void cargarEscuderias() {
        try {
            comboCampoEsc.removeAllItems();
            ArrayList<Escuderia> escuderias = this.gestion.getListaEscuderias();

        if (escuderias != null) {
            for (Escuderia e : escuderias) {
                comboCampoEsc.addItem(e);
            }
        }

        if (comboCampoEsc.getItemCount() > 0) {
            comboCampoEsc.setSelectedIndex(0);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error fatal: No se pudo cargar la lista de escuderías.", 
            "Error de Carga", 
            JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void cargarPilotos() {
    comboCampoPiloto.removeAllItems();
    ArrayList<Piloto> lista = gestion.getListaPilotos();
    if (lista != null) {
        for (Piloto p : lista) comboCampoPiloto.addItem(p);
    }
}
    
    private void cargarAutos() {
    comboCampoAuto.removeAllItems();
    ArrayList<Auto> lista = gestion.getListaAutos();
    if (lista != null) {
        for (Auto a : lista) comboCampoAuto.addItem(a);
    }
    }
    
    private void cargarMecanicos() {
    comboCampoMecanico.removeAllItems();
    ArrayList<Mecanico> lista = gestion.getListaMecanicos();
    if (lista != null) {
        for (Mecanico m : lista) comboCampoMecanico.addItem(m);
    }
}
    
    
    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton bntVolver;
    private javax.swing.JButton btnAsociar;
    private javax.swing.JButton btnBorrarEsc;
    private javax.swing.JButton btnEliminarAsociacion;
    private javax.swing.JComboBox<Auto> comboCampoAuto;
    private javax.swing.JComboBox<Escuderia> comboCampoEsc;
    private javax.swing.JComboBox<Mecanico> comboCampoMecanico;
    private javax.swing.JComboBox<Piloto> comboCampoPiloto;
    private javax.swing.JLabel fondoimg;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCampo2;
    private javax.swing.JLabel lblCampoEsc;
    private javax.swing.JLabel lblCampodF;
    private javax.swing.JLabel lblCampohF;
    private javax.swing.JLabel tituloRegistro;
    private javax.swing.JTextField txtCampodF;
    private javax.swing.JTextField txtCampohF;
    // End of variables declaration//GEN-END:variables
}
