/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import logica.Gestion;

/**
 *
 * @author Admin
 */
public class Pantalla extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pantalla.class.getName());

    /**
     * Creates new form Pantalla
     */
    private Gestion gestion;
    public Pantalla(Gestion gestion) {
        initComponents();
        this.gestion = gestion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        verstappen = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        asfalto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnGestionar = new javax.swing.JButton();
        btnPlanificar = new javax.swing.JButton();
        btnAsociarPilotos = new javax.swing.JButton();
        btnRegistrarResultados = new javax.swing.JButton();
        btnCalcularPuntajes = new javax.swing.JButton();
        btnGenerarInformes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        verstappen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verstappen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2483195.jpg"))); // NOI18N
        verstappen.setIconTextGap(0);
        verstappen.setPreferredSize(new java.awt.Dimension(1300, 600));
        jPanel2.add(verstappen, java.awt.BorderLayout.CENTER);

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 370, 600));

        jPanel3.setLayout(null);

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("¡Bienvenidos a Escuderías Unidas F1!");
        titulo.setAlignmentY(0.0F);
        jPanel3.add(titulo);
        titulo.setBounds(20, 80, 391, 32);

        asfalto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/asfalto.jpg"))); // NOI18N
        asfalto.setMaximumSize(new java.awt.Dimension(400, 600));
        asfalto.setMinimumSize(new java.awt.Dimension(400, 600));
        asfalto.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel3.add(asfalto);
        asfalto.setBounds(0, 0, 430, 130);

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 130));

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));
        jPanel1.setLayout(null);

        jPanel4.setOpaque(false);

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnGestionar.setText("GESTIONAR ESCUDERIAS");
        btnGestionar.setFocusPainted(false);
        btnGestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarActionPerformed(evt);
            }
        });

        btnPlanificar.setText("PLANIFICAR CARRERAS");
        btnPlanificar.setFocusPainted(false);
        btnPlanificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanificarActionPerformed(evt);
            }
        });

        btnAsociarPilotos.setText("ASOCIAR PILOTOS A AUTOS");
        btnAsociarPilotos.setFocusPainted(false);
        btnAsociarPilotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsociarPilotosActionPerformed(evt);
            }
        });

        btnRegistrarResultados.setText("REGISTRAR RESULTADOS");
        btnRegistrarResultados.setFocusPainted(false);

        btnCalcularPuntajes.setText("CALCULAR PUNTAJES");
        btnCalcularPuntajes.setFocusPainted(false);

        btnGenerarInformes.setText("GENERAR INFORMES");
        btnGenerarInformes.setFocusPainted(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRegistrarResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCalcularPuntajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGenerarInformes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAsociarPilotos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnGestionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnPlanificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnGestionar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnPlanificar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnAsociarPilotos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCalcularPuntajes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGenerarInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(120, 20, 190, 410);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2483195.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 600));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-30, -190, 1280, 720);

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 430, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlanificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlanificarActionPerformed
        VentanaPlanificar ventanaPlanificar = new VentanaPlanificar(this.gestion, this);
        
        ventanaPlanificar.setVisible(true);
        ventanaPlanificar.setLocationRelativeTo(null);
        this.dispose(); 
    }//GEN-LAST:event_btnPlanificarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
    // Crea una instancia de la ventana nueva a abrir
        VentanaRegistrar pantallaRegistro = new VentanaRegistrar(this.gestion, this);

    // Hacerla visible
            pantallaRegistro.setVisible(true);

    // Centrar en la pantalla
            pantallaRegistro.setLocationRelativeTo(null);

    // Cerrar ventana actual
            this.dispose();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnGestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarActionPerformed
        VentanaGestionar vGestionar = new VentanaGestionar(this.gestion, this);
        vGestionar.setVisible(true);
        vGestionar.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnGestionarActionPerformed

    private void btnAsociarPilotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsociarPilotosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsociarPilotosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asfalto;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnAsociarPilotos;
    private javax.swing.JButton btnCalcularPuntajes;
    private javax.swing.JButton btnGenerarInformes;
    private javax.swing.JButton btnGestionar;
    private javax.swing.JButton btnPlanificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegistrarResultados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel verstappen;
    // End of variables declaration//GEN-END:variables
}
