package gui;

/**
 *
 * @author Admin
 */
import java.util.ArrayList;
import javax.swing.JFrame;


/**
 * Representa una ventana (JFrame) simple diseñada para mostrar la salida
 * de un informe.
 * * Consiste en un JTextArea no editable dentro de un JScrollPane para mostrar
 * el texto del informe (recibido como un ArrayList de Strings) y un botón
 * "VOLVER" para regresar a la ventana anterior que la invocó.
 *
 * @author Admin
 */
public class SalidaInforme extends javax.swing.JFrame {
    /** Referencia a la ventana anterior (ej: FormularioInformes) para poder volver. */
    private JFrame ventanaAnterior;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SalidaInforme.class.getName());

    /**
     * Crea un nuevo formulario SalidaInforme.
     * Inicializa los componentes, guarda la referencia a la ventana anterior,
     * y llama a {@link #mostrarInforme(ArrayList)} para poblar el área de texto.
     *
     * @param informe El ArrayList<String> que contiene las líneas del informe a mostrar.
     * @param ventanaAnterior La ventana (JFrame) que invocó esta, para poder volver a ella.
     */
    public SalidaInforme(ArrayList<String> informe, JFrame ventanaAnterior) {
        initComponents();
        this.ventanaAnterior = ventanaAnterior;
        txtSalida.setEditable(false);

        // Llamamos al método que llena el TextArea
        mostrarInforme(informe);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnVolver)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Manejador del evento del botón 'Volver'.
     * Cierra (dispose) esta ventana de informe y vuelve a hacer visible
     * la 'ventanaAnterior' (el formulario de configuración de informes).
     *
     * @param evt El evento de acción.
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.ventanaAnterior.setVisible(true); // Muestra la ventana anterior (VentanaInformes)
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed
    
    /**
     * Toma un ArrayList de Strings y lo formatea en el JTextArea 'txtSalida'.
     * Cada elemento del ArrayList se trata como una nueva línea en el informe,
     * añadiendo un salto de línea ("\n") después de cada uno.
     * Finalmente, sitúa el cursor al inicio del texto.
     *
     * @param informe La lista de líneas de String que componen el informe.
     */
    private void mostrarInforme(ArrayList<String> informe) {
        StringBuilder sb = new StringBuilder();
        for (String linea : informe) {
            sb.append(linea);
            sb.append("\n"); // Agrega un salto de línea
        }
        txtSalida.setText(sb.toString());

        // Mueve el cursor al inicio del texto
        txtSalida.setCaretPosition(0); 
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
