package gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class VentanaPlanificar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPlanificar.class.getName());
    private final Gestion gestion;
    private final Pantalla pantallaAnterior;

    /**
     * Creates new form FormularioRegistro
     */
    public VentanaPlanificar(Gestion gestion, Pantalla pantallaAnterior) {
        initComponents();
        
        this.gestion = gestion;
        this.pantallaAnterior = pantallaAnterior;
        cargarCircuitos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bntVolver = new javax.swing.JButton();
        tituloRegistro = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblCampo1 = new javax.swing.JLabel();
        txtCampo1 = new javax.swing.JTextField();
        lblCampo2 = new javax.swing.JLabel();
        txtCampo2 = new javax.swing.JTextField();
        lblCampo3 = new javax.swing.JLabel();
        txtCampo3 = new javax.swing.JTextField();
        lblCampo4 = new javax.swing.JLabel();
        comboCampoCircuitos = new javax.swing.JComboBox<>();
        bntGuardar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        fondoimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(null);

        bntVolver.setText("VOLVER");
        bntVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVolverActionPerformed(evt);
            }
        });
        jPanel2.add(bntVolver);
        bntVolver.setBounds(6, 10, 90, 27);

        tituloRegistro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloRegistro.setText("PLANIFICAR CARRERA");
        tituloRegistro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(tituloRegistro);
        tituloRegistro.setBounds(0, 0, 360, 110);

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 110));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCampo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCampo1.setText("Fecha (aaaammdd):");
        jPanel3.add(lblCampo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 25));

        txtCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampo1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtCampo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 150, -1));

        lblCampo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCampo2.setText("Hora (hhmm):");
        jPanel3.add(lblCampo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 25));
        jPanel3.add(txtCampo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 150, -1));

        lblCampo3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCampo3.setText("Número de vueltas:");
        jPanel3.add(lblCampo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 150, 20));
        jPanel3.add(txtCampo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        lblCampo4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCampo4.setText("Circuito:");
        jPanel3.add(lblCampo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 25));

        comboCampoCircuitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCampoCircuitosActionPerformed(evt);
            }
        });
        jPanel3.add(comboCampoCircuitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 150, -1));

        bntGuardar.setText("GUARDAR");
        bntGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(bntGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 100, 40));

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 360, 290));

        fondoimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/f1logo.png"))); // NOI18N
        fondoimg.setPreferredSize(new java.awt.Dimension(310, 320));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoimg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoimg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 340, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVolverActionPerformed
        this.pantallaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bntVolverActionPerformed

    private void txtCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampo1ActionPerformed
        
    }//GEN-LAST:event_txtCampo1ActionPerformed

    private void bntGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarActionPerformed
        try {
            // 1. Leer datos de los campos
            String fecha = txtCampo1.getText();
            String hora = txtCampo2.getText();
            String vueltasStr = txtCampo3.getText();
            Circuito circuito = (Circuito) comboCampoCircuitos.getSelectedItem();

            // 2. Validación
            if (fecha.isEmpty() || hora.isEmpty() || vueltasStr.isEmpty() || circuito == null) {
                JOptionPane.showMessageDialog(this, "Debe completar fecha, hora, vueltas y seleccionar un circuito.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 3. Conversión
            int vueltas = Integer.parseInt(vueltasStr);

            // 4. Llamar a la lógica
            this.gestion.planificarCarrera(fecha, vueltas, hora, circuito);

            JOptionPane.showMessageDialog(this, "Carrera planificada con éxito.");

//            // Opcional: limpiar campos
            txtCampo1.setText("");
            txtCampo2.setText("");
            txtCampo3.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El número de vueltas debe ser un número válido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
    }//GEN-LAST:event_bntGuardarActionPerformed

    private void comboCampoCircuitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCampoCircuitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCampoCircuitosActionPerformed

    private void cargarCircuitos() {
        try {
            comboCampoCircuitos.removeAllItems();

            ArrayList<Circuito> circuitos = this.gestion.getListaCircuitos();

            if (circuitos != null) {
                for (Circuito c : circuitos) {
                    comboCampoCircuitos.addItem(c); // Añade el objeto Circuito
                }
            }

            if (comboCampoCircuitos.getItemCount() > 0) {
                comboCampoCircuitos.setSelectedIndex(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error fatal: No se pudo cargar la lista de circuitos.", 
                "Error de Carga", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
//  private void cargarPaises() {
//        try {
//            // 1. Limpia el combo (borra "Item 1", "Item 2", etc.)
//            comboCampo2.removeAllItems(); 
//            comboCampoCircuito.removeAllItems(); 
//            
//            // 2. Le pide la lista de países a tu objeto 'miGestion'
//            //    (Esto usa el método que creamos en Gestion.java)
//            ArrayList<Pais> listaDePaises = this.gestion.getListaPais();
//
//            // 3. Recorre la lista y añade cada OBJETO 'Pais' al combo
//            if (listaDePaises != null) {
//                for (Pais p : listaDePaises) {
//                    comboCampo2.addItem(p);
//                    comboCampoCircuito.addItem(p);
//                }
//            }
//            
//            // 4. (Opcional) Pone el primero como seleccionado
//            if (comboCampo2.getItemCount() > 0) {
//                comboCampo2.setSelectedIndex(0);
//            }
//            if (comboCampoCircuito.getItemCount() > 0) {
//                comboCampoCircuito.setSelectedIndex(0);
//            }
//
//        } catch (Exception e) {
//            // Muestra un error si 'miGestion' falla
//            JOptionPane.showMessageDialog(this, 
//                "Error fatal: No se pudo cargar la lista de países.", 
//                "Error de Carga", 
//                JOptionPane.ERROR_MESSAGE);
//            
//            // También usamos el 'logger' que ya tienes en tu clase
//            logger.severe("Error al cargar países: " + e.getMessage());
//        }
//  }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton bntGuardar;
    private javax.swing.JButton bntVolver;
    private javax.swing.JComboBox<Circuito> comboCampoCircuitos;
    private javax.swing.JLabel fondoimg;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCampo1;
    private javax.swing.JLabel lblCampo2;
    private javax.swing.JLabel lblCampo3;
    private javax.swing.JLabel lblCampo4;
    private javax.swing.JLabel tituloRegistro;
    private javax.swing.JTextField txtCampo1;
    private javax.swing.JTextField txtCampo2;
    private javax.swing.JTextField txtCampo3;
    // End of variables declaration//GEN-END:variables
}
