package gui;

import logica.*;

/**
 * Representa el sub-menú de "Gestión" de la aplicación.
 * Esta ventana (JFrame) actúa como un navegador que redirige al usuario
 * al formulario dinámico {@link FormularioGestionar}, pasándole
 * un "modo" específico (ej: "PILOTO", "AUTO", "BORRAR_ESCUDERIA")
 * según el botón presionado.
 *
 * @author Admin
 */
public class VentanaGestionar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaGestionar.class.getName());
    /** Referencia al controlador principal de la lógica de negocio ({@link Gestion}). */
    private final Gestion gestion;
    /** Referencia a la pantalla principal ({@link Pantalla}) que la invocó, para poder volver. */
    private final Pantalla pantallaAnterior;

    /**
     * Crea un nuevo formulario VentanaGestionar (sub-menú de gestión).
     *
     * @param gestion La instancia del controlador de lógica principal ({@link Gestion}).
     * @param pantallaAnterior La pantalla principal ({@link Pantalla}) a la que se debe volver.
     */
    public VentanaGestionar(Gestion gestion, Pantalla pantallaAnterior) {
        initComponents();
        this.gestion = gestion;
        this.pantallaAnterior = pantallaAnterior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bntVolver = new javax.swing.JButton();
        tituloRegistro = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBorrarEscuderia = new javax.swing.JButton();
        btnPilotos = new javax.swing.JButton();
        btnAutos = new javax.swing.JButton();
        btnMecanicos = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        fondoimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(null);

        bntVolver.setText("VOLVER");
        bntVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVolverActionPerformed(evt);
            }
        });
        jPanel2.add(bntVolver);
        bntVolver.setBounds(6, 10, 90, 27);

        tituloRegistro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloRegistro.setText("GESTIONAR");
        tituloRegistro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(tituloRegistro);
        tituloRegistro.setBounds(0, 0, 360, 60);

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 60));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBorrarEscuderia.setText("BORRAR ESCUDERIAS");
        btnBorrarEscuderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarEscuderiaActionPerformed(evt);
            }
        });
        jPanel3.add(btnBorrarEscuderia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 270, 40));

        btnPilotos.setText("GESTIONAR PILOTOS EN ESCUDERIAS");
        btnPilotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilotosActionPerformed(evt);
            }
        });
        jPanel3.add(btnPilotos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 270, 40));

        btnAutos.setText("GESTIONAR AUTOS EN ESCUDERIAS");
        btnAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutosActionPerformed(evt);
            }
        });
        jPanel3.add(btnAutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 270, 40));

        btnMecanicos.setText("GESTIONAR MECÁNICOS EN ESCUDERIAS");
        btnMecanicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMecanicosActionPerformed(evt);
            }
        });
        jPanel3.add(btnMecanicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 270, 40));

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 360, 340));

        fondoimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/f1logo.png"))); // NOI18N
        fondoimg.setPreferredSize(new java.awt.Dimension(310, 320));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoimg, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoimg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 340, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Manejador del botón 'Volver'.
     * Cierra (dispose) esta ventana y vuelve a hacer visible la pantalla
     * principal ({@link Pantalla}).
     * @param evt El evento de acción.
     */
    private void bntVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVolverActionPerformed
        this.pantallaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bntVolverActionPerformed

    /**
     * Manejador del botón 'Gestionar Autos'.
     * Abre el {@link FormularioGestionar} en modo "AUTO".
     * Cierra esta ventana.
     * @param evt El evento de acción.
     */
    private void btnAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutosActionPerformed
        FormularioGestionar fGestion = new FormularioGestionar("AUTO", this.gestion, this);
        fGestion.setVisible(true);
        fGestion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnAutosActionPerformed

    /**
     * Manejador del botón 'Borrar Escuderias'.
     * Abre el {@link FormularioGestionar} en modo "BORRAR_ESCUDERIA".
     * Cierra esta ventana.
     * @param evt El evento de acción.
     */
    private void btnBorrarEscuderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarEscuderiaActionPerformed
        FormularioGestionar fGestion = new FormularioGestionar("BORRAR_ESCUDERIA", this.gestion, this);
        fGestion.setVisible(true);
        fGestion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnBorrarEscuderiaActionPerformed

    /**
     * Manejador del botón 'Gestionar Pilotos'.
     * Abre el {@link FormularioGestionar} en modo "PILOTO".
     * Cierra esta ventana.
     * @param evt El evento de acción.
     */
    private void btnPilotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilotosActionPerformed
        FormularioGestionar fGestion = new FormularioGestionar("PILOTO", this.gestion, this);
        fGestion.setVisible(true);
        fGestion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnPilotosActionPerformed

    /**
     * Manejador del botón 'Gestionar Mecánicos'.
     * Abre el {@link FormularioGestionar} en modo "MECANICO".
     * Cierra esta ventana.
     * @param evt El evento de acción.
     */
    private void btnMecanicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMecanicosActionPerformed
        FormularioGestionar fGestion = new FormularioGestionar("MECANICO", this.gestion, this);
        fGestion.setVisible(true);
        fGestion.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnMecanicosActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton bntVolver;
    private javax.swing.JButton btnAutos;
    private javax.swing.JButton btnBorrarEscuderia;
    private javax.swing.JButton btnMecanicos;
    private javax.swing.JButton btnPilotos;
    private javax.swing.JLabel fondoimg;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel tituloRegistro;
    // End of variables declaration//GEN-END:variables
}
