/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import logica.Gestion;

/**
 *
 * @author Admin
 */
public class VentanaRegistrar extends javax.swing.JFrame {
    private Gestion gestion;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaRegistrar.class.getName());

    /**
     * Creates new form VentanaRegistrar
     */
    public VentanaRegistrar(Gestion gestion) {
        initComponents();
        this.gestion = gestion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bntVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        bntRegistrarPiloto = new javax.swing.JButton();
        bntRegistrarMecanico = new javax.swing.JButton();
        bntRegistrarAuto = new javax.swing.JButton();
        bntRegistrarEscuderia = new javax.swing.JButton();
        bntRegistrarCircuito = new javax.swing.JButton();
        bntRegistrarPais = new javax.swing.JButton();
        bntRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(null);
        setResizable(false);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú para registrar");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        bntVolver.setText("VOLVER");
        bntVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(118, 118, 118))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 220));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿Qué desea hacer?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 800, 50));

        bntRegistrarPiloto.setText("Registrar Piloto");
        bntRegistrarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistrarPilotoActionPerformed(evt);
            }
        });

        bntRegistrarMecanico.setText("Registrar Mecánico");
        bntRegistrarMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistrarMecanicoActionPerformed(evt);
            }
        });

        bntRegistrarAuto.setText("Registrar Auto");
        bntRegistrarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistrarAutoActionPerformed(evt);
            }
        });

        bntRegistrarEscuderia.setText("Registrar Escudería");
        bntRegistrarEscuderia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistrarEscuderiaActionPerformed(evt);
            }
        });

        bntRegistrarCircuito.setText("Registrar Circuito");
        bntRegistrarCircuito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistrarCircuitoActionPerformed(evt);
            }
        });

        bntRegistrarPais.setText("Registrar País");
        bntRegistrarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegistrarPaisActionPerformed(evt);
            }
        });

        bntRegistrar.setText("Registar...");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntRegistrarMecanico)
                            .addComponent(bntRegistrarAuto)
                            .addComponent(bntRegistrarPais)
                            .addComponent(bntRegistrarPiloto))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntRegistrarEscuderia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bntRegistrarCircuito, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bntRegistrar, bntRegistrarAuto, bntRegistrarCircuito, bntRegistrarEscuderia, bntRegistrarMecanico, bntRegistrarPais, bntRegistrarPiloto});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bntRegistrarPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntRegistrarMecanico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntRegistrarAuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntRegistrarEscuderia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntRegistrarCircuito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntRegistrarPais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntRegistrar)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bntRegistrar, bntRegistrarAuto, bntRegistrarCircuito, bntRegistrarEscuderia, bntRegistrarMecanico, bntRegistrarPais, bntRegistrarPiloto});

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 800, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVolverActionPerformed
        Pantalla nuevaPantalla = new Pantalla();
        nuevaPantalla.setVisible(true);
        nuevaPantalla.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bntVolverActionPerformed

    private void bntRegistrarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistrarPilotoActionPerformed
        FormularioRegistro formularioRegistro = new FormularioRegistro("PILOTO", this.gestion);
        formularioRegistro.setVisible(true);
        formularioRegistro.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bntRegistrarPilotoActionPerformed

    private void bntRegistrarMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistrarMecanicoActionPerformed
        FormularioRegistro formularioRegistro = new FormularioRegistro("MECANICO", this.gestion);
        formularioRegistro.setVisible(true);
        formularioRegistro.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bntRegistrarMecanicoActionPerformed

    private void bntRegistrarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistrarAutoActionPerformed
        FormularioRegistro formularioRegistro = new FormularioRegistro("AUTO", this.gestion);
        formularioRegistro.setVisible(true);
        formularioRegistro.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bntRegistrarAutoActionPerformed

    private void bntRegistrarEscuderiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistrarEscuderiaActionPerformed
        FormularioRegistro formularioRegistro = new FormularioRegistro("ESCUDERIA", this.gestion);
        formularioRegistro.setVisible(true);
        formularioRegistro.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bntRegistrarEscuderiaActionPerformed

    private void bntRegistrarCircuitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistrarCircuitoActionPerformed
        FormularioRegistro formularioRegistro = new FormularioRegistro("CIRCUITO", this.gestion);
        formularioRegistro.setVisible(true);
        formularioRegistro.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bntRegistrarCircuitoActionPerformed

    private void bntRegistrarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegistrarPaisActionPerformed
        FormularioRegistro formularioRegistro = new FormularioRegistro("PAIS", this.gestion);
        formularioRegistro.setVisible(true);
        formularioRegistro.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_bntRegistrarPaisActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton bntRegistrar;
    private javax.swing.JButton bntRegistrarAuto;
    private javax.swing.JButton bntRegistrarCircuito;
    private javax.swing.JButton bntRegistrarEscuderia;
    private javax.swing.JButton bntRegistrarMecanico;
    private javax.swing.JButton bntRegistrarPais;
    private javax.swing.JButton bntRegistrarPiloto;
    private javax.swing.JButton bntVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
