package gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Representa la ventana (JFrame) dedicada a la planificación (creación) de
 * nuevas {@link logica.Carrera}.
 *
 * Esta interfaz de usuario recopila la fecha, hora, número de vueltas y el
 * circuito
 * para una nueva carrera. Incluye validaciones robustas para asegurar que los
 * datos
 * sean correctos (formatos, rangos lógicos) y que se cumplan las reglas de
 * negocio
 * (ej. no duplicar un circuito en el mismo año).
 *
 * @author Admin 
 */
public class VentanaPlanificar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPlanificar.class.getName());
    /** Referencia al controlador principal de la lógica de negocio ({@link Gestion}). */
    private final Gestion gestion;
    /** Referencia a la pantalla principal ({@link Pantalla}) que la invocó, para poder volver. */
    private final Pantalla pantallaAnterior;

    /**
     * Crea un nuevo formulario VentanaPlanificar.
     *
     * @param gestion La instancia del controlador de lógica principal ({@link Gestion}).
     * @param pantallaAnterior La pantalla principal ({@link Pantalla}) a la que se debe volver.
     */
    public VentanaPlanificar(Gestion gestion, Pantalla pantallaAnterior) {
        initComponents();
        
        this.gestion = gestion;
        this.pantallaAnterior = pantallaAnterior;
        cargarCircuitos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bntVolver = new javax.swing.JButton();
        tituloRegistro = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblCampo1 = new javax.swing.JLabel();
        txtCampo1 = new javax.swing.JTextField();
        lblCampo2 = new javax.swing.JLabel();
        txtCampo2 = new javax.swing.JTextField();
        lblCampo3 = new javax.swing.JLabel();
        txtCampo3 = new javax.swing.JTextField();
        lblCampo4 = new javax.swing.JLabel();
        comboCampoCircuitos = new javax.swing.JComboBox<>();
        bntGuardar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        fondoimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(null);

        bntVolver.setText("VOLVER");
        bntVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntVolverActionPerformed(evt);
            }
        });
        jPanel2.add(bntVolver);
        bntVolver.setBounds(6, 10, 90, 27);

        tituloRegistro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tituloRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloRegistro.setText("PLANIFICAR CARRERA");
        tituloRegistro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(tituloRegistro);
        tituloRegistro.setBounds(0, 0, 360, 110);

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 110));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCampo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCampo1.setText("Fecha (aaaammdd):");
        jPanel3.add(lblCampo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 150, 25));

        txtCampo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampo1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtCampo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 150, -1));

        lblCampo2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCampo2.setText("Hora (hhmm):");
        jPanel3.add(lblCampo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 150, 25));
        jPanel3.add(txtCampo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 150, -1));

        lblCampo3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCampo3.setText("Número de vueltas:");
        jPanel3.add(lblCampo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 150, 20));
        jPanel3.add(txtCampo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, -1));

        lblCampo4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCampo4.setText("Circuito:");
        jPanel3.add(lblCampo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 25));

        comboCampoCircuitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCampoCircuitosActionPerformed(evt);
            }
        });
        jPanel3.add(comboCampoCircuitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 150, -1));

        bntGuardar.setText("GUARDAR");
        bntGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(bntGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 100, 40));

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 360, 290));

        fondoimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/f1logo.png"))); // NOI18N
        fondoimg.setPreferredSize(new java.awt.Dimension(310, 320));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoimg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoimg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 340, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Manejador del botón 'Volver'.
     * Cierra (dispose) esta ventana y vuelve a hacer visible la pantalla
     * principal ({@link Pantalla}).
     * @param evt El evento de acción.
     */
    private void bntVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntVolverActionPerformed
        this.pantallaAnterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bntVolverActionPerformed

    private void txtCampo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampo1ActionPerformed
        
    }//GEN-LAST:event_txtCampo1ActionPerformed
    
    /**
     * Manejador del evento del botón 'GUARDAR'.
     * Es el controlador principal de esta ventana.
     * 1. Llama a {@link #validarFormularioPlanificar()} para revisar los datos.
     * 2. Si la validación falla, captura la Excepción y muestra el error.
     * 3. Si la validación tiene éxito, llama a {@link #guardarPlanificar()} para
     * crear la carrera y persistirla.
     * 4. Muestra un mensaje de éxito.
     *
     * @param evt El evento de acción.
     */
    private void bntGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarActionPerformed
        try {
         // 1. Llama a todas las validaciones
         // (Si algo falla, salta directamente al 'catch')
         validarFormularioPlanificar();

         // 2. Si las validaciones pasaron, llama a guardar
         guardarPlanificar();

         // 3. Muestra el mensaje de éxito
         JOptionPane.showMessageDialog(this, "Carrera planificada con éxito.");

        } catch (Exception e) {
         // 4. Muestra cualquier error de validación que haya ocurrido
         JOptionPane.showMessageDialog(this, 
             "Error al guardar: " + e.getMessage(), // Muestra el mensaje de nuestra validación
             "Error de Validación", 
             JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_bntGuardarActionPerformed

    
    private void comboCampoCircuitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCampoCircuitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCampoCircuitosActionPerformed

    /**
     * Carga la lista de {@link Circuito} desde la capa de gestión
     * y las añade al JComboBox 'comboCampoCircuitos'.
     */
    private void cargarCircuitos() {
        try {
            comboCampoCircuitos.removeAllItems();

            ArrayList<Circuito> circuitos = this.gestion.getListaCircuitos();

            if (circuitos != null) {
                for (Circuito c : circuitos) {
                    comboCampoCircuitos.addItem(c); // Añade el objeto Circuito
                }
            }

            if (comboCampoCircuitos.getItemCount() > 0) {
                comboCampoCircuitos.setSelectedIndex(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error fatal: No se pudo cargar la lista de circuitos.", 
                "Error de Carga", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
    // Validaciones
    
    /**
     * Ejecuta un conjunto de reglas de validación para el formulario de
     * planificación de carrera.
     * Comprueba:
     * 1. Campos vacíos.
     * 2. Formato de Fecha (YYYYMMDD) y Hora (HHMM).
     * 3. Rangos lógicos (Mes 01-12, Día 01-31, Hora 00-23, Min 00-59).
     * 4. Formato de Vueltas (numérico) y Rango (20-80).
     * 5. Regla de Negocio: Que el circuito no esté ya planificado para ese
     * mismo año.
     *
     * @throws Exception Si alguna regla de validación no se cumple. El mensaje
     * de la excepción está listo para mostrarse al usuario.
     */
    private void validarFormularioPlanificar() throws Exception {
    
        // --- 1. LECTURA DE DATOS ---
        String fechaStr = txtCampo1.getText().trim();
        String horaStr = txtCampo2.getText().trim();
        String vueltasStr = txtCampo3.getText().trim();
        Object circuitoObj = comboCampoCircuitos.getSelectedItem();

        // --- 2. VALIDACIÓN DE CAMPOS VACÍOS ---
        if (fechaStr.isEmpty() || horaStr.isEmpty() || vueltasStr.isEmpty() || circuitoObj == null) {
            throw new Exception("Debe completar todos los campos (Fecha, Hora, Vueltas y Circuito).");
        }

        // --- 3. VALIDACIÓN DE FORMATO (FECHA) ---
        if (!fechaStr.matches("\\d{8}")) {
            throw new Exception("La 'Fecha' debe tener 8 números en formato YYYYMMDD (ej: 20251026).");
        }

        // --- 4. VALIDACIÓN DE FORMATO (HORA) ---
        if (!horaStr.matches("\\d{4}")) {
            throw new Exception("La 'Hora' debe tener 4 números en formato HHMM (ej: 1430).");
        }

        // --- 5. VALIDACIÓN DE RANGOS LÓGICOS (FECHA Y HORA) ---
        try {
            // Extraemos las partes de la fecha
            String anioNuevo = fechaStr.substring(0, 4);
            int mes = Integer.parseInt(fechaStr.substring(4, 6)); // (MM)
            int dia = Integer.parseInt(fechaStr.substring(6, 8)); // (DD)

            // ¡Validación de Mes (01-12)!
            if (mes < 1 || mes > 12) {
                throw new Exception("El Mes (MM) en la fecha debe estar entre 01 y 12.");
            }

            // ¡Validación de Día (01-31)!
            // (No validamos 30, 31 o bisiesto para simplificar, solo el rango básico)
            if (dia < 1 || dia > 31) {
                throw new Exception("El Día (DD) en la fecha debe estar entre 01 y 31.");
            }

            // Extraemos las partes de la hora
            int hora = Integer.parseInt(horaStr.substring(0, 2)); // (HH)
            int min = Integer.parseInt(horaStr.substring(2, 4)); // (MM)

            // ¡Validación de Hora (00-23)
            if (hora < 0 || hora > 23) {
                throw new Exception("La Hora (HH) debe estar entre 00 y 23.");
            }

            // ¡Validación de Minutos (00-59)
            if (min < 0 || min > 59) {
                throw new Exception("Los Minutos (MM) deben estar entre 00 y 59.");
            }

        } catch (Exception e) {
            // Si falla el substring o el parseInt (aunque ya validamos el formato)
            throw new Exception("La fecha o la hora tienen un formato numérico inválido.");
        }


        // --- 6. VALIDACIÓN DE FORMATO Y RANGO (VUELTAS) ---
        int vueltas;
        try {
            vueltas = Integer.parseInt(vueltasStr);
        } catch (NumberFormatException e) {
            throw new Exception("El 'Número de vueltas' debe ser un número (no se permiten letras).");
        }

        // ¡Validación de rango 20-80!
        if (vueltas < 20 || vueltas > 80) {
            throw new Exception("El 'Número de vueltas' debe estar entre 20 y 80.");
        }

        // --- 7. VALIDACIÓN DE LÓGICA (Circuito duplicado en el año) ---
        String anioNuevo = fechaStr.substring(0, 4); // Re-leemos el año (String)
        Circuito circuitoSeleccionado = (Circuito) circuitoObj;

        ArrayList<Carrera> carrerasExistentes = this.gestion.getListaCarreras();

        if (carrerasExistentes != null) {
            for (Carrera carrera : carrerasExistentes) {
                if (carrera.getCircuito() == null || carrera.getFechaRealizacion() == null || carrera.getFechaRealizacion().length() < 8) {
                    continue;
                }

                boolean mismoCircuito = carrera.getCircuito().equals(circuitoSeleccionado);
                String anioExistente = carrera.getFechaRealizacion().substring(0, 4);
                boolean mismoAnio = anioExistente.equals(anioNuevo);

                if (mismoCircuito && mismoAnio) {
                    throw new Exception("Ya existe una carrera planificada en '" + 
                                      circuitoSeleccionado.getNombre() + "' para el año " + anioNuevo + ".");
                }
            }
        }
    }
    
    /**
     * Lee los datos (ya validados) del formulario y llama a la capa de
     * 'gestion' para crear y persistir la nueva carrera.
     * Finalmente, limpia los campos de texto del formulario.
     */
    private void guardarPlanificar() {
        // Leemos los datos
        String fecha = txtCampo1.getText().trim();
        String hora = txtCampo2.getText().trim();
        int vueltas = Integer.parseInt(txtCampo3.getText().trim()); // Es seguro parsear
        Circuito circuito = (Circuito) comboCampoCircuitos.getSelectedItem();

        // Llamamos a la lógica de negocio
        this.gestion.planificarCarrera(fecha, vueltas, hora, circuito);

        // Limpiar campos después de guardar
        txtCampo1.setText("");
        txtCampo2.setText("");
        txtCampo3.setText("");
    }
 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton bntGuardar;
    private javax.swing.JButton bntVolver;
    private javax.swing.JComboBox<Circuito> comboCampoCircuitos;
    private javax.swing.JLabel fondoimg;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCampo1;
    private javax.swing.JLabel lblCampo2;
    private javax.swing.JLabel lblCampo3;
    private javax.swing.JLabel lblCampo4;
    private javax.swing.JLabel tituloRegistro;
    private javax.swing.JTextField txtCampo1;
    private javax.swing.JTextField txtCampo2;
    private javax.swing.JTextField txtCampo3;
    // End of variables declaration//GEN-END:variables
}
